// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDummyKeyForWeb-ReplaceWithRealKey',
    appId: '1:1088833222702:web:dummyappid',
    messagingSenderId: '1088833222702',
    projectId: 'safe-space-69052',
    authDomain: 'safe-space-69052.firebaseapp.com',
    storageBucket: 'safe-space-69052.appspot.com',
    measurementId: 'G-MEASUREMENT_ID',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDummyKeyForAndroid-ReplaceWithRealKey',
    appId: '1:1088833222702:android:dummyappid',
    messagingSenderId: '1088833222702',
    projectId: 'safe-space-69052',
    storageBucket: 'safe-space-69052.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDummyKeyForIOS-ReplaceWithRealKey',
    appId: '1:1088833222702:ios:dummyappid',
    messagingSenderId: '1088833222702',
    projectId: 'safe-space-69052',
    storageBucket: 'safe-space-69052.appspot.com',
    iosBundleId: 'com.example.safeSpace',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDummyKeyForIOS-ReplaceWithRealKey',
    appId: '1:1088833222702:ios:dummyappid',
    messagingSenderId: '1088833222702',
    projectId: 'safe-space-69052',
    storageBucket: 'safe-space-69052.appspot.com',
    iosBundleId: 'com.example.safeSpace',
  );
}

